[workspace]

members = [
    "d1_calorie_counting",
    "d2_rock_paper_scissors",
    "d3_rucksack",
    "d4_camp_cleanup",
    "d5_supply_stacks",
    "d6_tuning_trouble",
    "d7_no_space_left",
    "d8_treetop_tree_house"
]
