[package]
name = "d15_beacon_exclusive_zone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# aoc_utils = { version = "0.1.0", path = "../aoc_utils" }
